export const CONTENT_TYPE = {
    TEXT: "TEXT",
    INPUT: "INPUT",
    CODE: "CODE",
    HEADER_PRIMARY: "HEADER_PRIMARY",
    HEADER_SECONDARY: "HEADER_SECONDARY",
    HEADER_TERTIARY: "HEADER_TERTIARY",
    VARIABLE: "VARIABLE",
};
