export const LIGHT_THEME = {
    BACKGROUND_PRIMARY: "#FFFFFF",
    BACKGROUND_SECONDARY: "#E2E8F0",
    HEADER_PRIMARY: "#000000",
    HEADER_SECONDARY: "#2D3748",
    TEXT_PRIMARY: "#718096",
    TEXT_SECONDARY: "#A0AEC0"
};

export const DARK_THEME = {
    BACKGROUND_PRIMARY: "#282a36",
    BACKGROUND_SECONDARY: "#44475a",
    HEADER_PRIMARY: "#8be9fd",
    HEADER_SECONDARY: "#f1fa8c",
    TEXT_PRIMARY: "#f8f8f2",
    TEXT_SECONDARY: "#ff79c6"
};
